[package]
name = "mnasm"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "codegen", "parser","tokenizer", "util"]


[dependencies]
tokenizer = { path = "./tokenizer"}
util = { path = "./util"}
parser = {path = "./parser"}
